# Lost in Pandas - Part 5
> The series of Pandas tips and tricks

- toc: true
- badges: true
- comments: true
- keywords: [pandas, python, data analysis, pandas tips and tricks, advance pandas, data transformation in pandas]
- tags: [Pandas, Data Analysis]
- author: Nodar Okroshiashvili
- categories: [DataScience]

## Introduction

In this notebook I'll show how to assign new value for each unique group in Pandas DataFrame.

In [1]:
#collapse-show
import pandas as pd

In [2]:
data = {"ID": [1, 1, 1, 2, 2, 3, 3], "class": ["Lower", "Moderate", "Moderate", "Lower", "High", "High", "Lower"]}

Let convert this dictionary into Pandas DataFrame and see what data we have.

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   ID     class
0   1     Lower
1   1  Moderate
2   1  Moderate
3   2     Lower
4   2      High
5   3      High
6   3     Lower

Now, let assign new values according to ```class``` column and then rearrange ```class``` column in order to assign new group names.

In [5]:
value_map = {"Lower": 33, "Moderate": 34, "High": 40}

df["new"] = df["class"].map(value_map)

df

   ID     class  new
0   1     Lower   33
1   1  Moderate   34
2   1  Moderate   34
3   2     Lower   33
4   2      High   40
5   3      High   40
6   3     Lower   33

In [6]:
df["Max"] = df.set_index("class").groupby("ID")["new"].transform("idxmax").values

df

   ID     class  new       Max
0   1     Lower   33  Moderate
1   1  Moderate   34  Moderate
2   1  Moderate   34  Moderate
3   2     Lower   33      High
4   2      High   40      High
5   3      High   40      High
6   3     Lower   33      High

If we want only first values per group

In [7]:
df["Max"] = df["Max"].mask(df["ID"].duplicated(), "")

df

   ID     class  new       Max
0   1     Lower   33  Moderate
1   1  Moderate   34
2   1  Moderate   34
3   2     Lower   33      High
4   2      High   40
5   3      High   40      High
6   3     Lower   33